### ISSUE TITLE
puppetlabs-powershell got updated in january to 3.0.1

### ISSUE THREAD

**Issue by dominik-ba** [voxpupuli/puppet-download_file#100]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version: 4.0.0

## Any additional information you'd like to impart

Can't the dependencies be updated to reflect the newest release or is was there really an breaking change introduced with the newer powershell module version?
Link to the module: https://forge.puppet.com/puppetlabs/powershell

**Comment by veronesip** [comment]
Just to add that puppetlabs/powershell last release is v4.0.0 (2020-07-07)

**Comment by vegaaz** [comment]
Just experienced the same issue...
Issue is open since May, will there be a 'fix' soon ?

@dominik-ba thanks for reporting! :+1:

**Comment by kenyon** [comment]
Pull requests gladly accepted!

**Comment by zilchms** [comment]
fixed in #111
