### ISSUE TITLE
puppetlabs/stdlib version below 6.0.0

### ISSUE THREAD

**Issue by xtimmu** [voxpupuli/puppet-download_file#96]
Hello,

Is there any particular reason why puppetlabs/stdlib version is bound below 6.0.0? The latest version is 6.2.0 and I'm experiencing dependency conflicts when mixing download_file with other modules.

Regards,

xtimmu

**Comment by dhoppe** [comment]
There is no particular reason. Just that we manage over 100 Puppet modules in our spare time. ;)
